name: CI/CD Docker Deploy to VPS - GundarConnect FE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ashafaatadhis/gundarconnect-fe:latest

      - name: SSH to VPS and deploy frontend
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          script: |
            cd ~/gundarconnect-be

            echo "📦 Pulling latest be image..."
            docker compose pull

            echo "🔁 Restarting be container..."
            docker compose down
            docker compose up -d --build

            echo "✅ Backend GundarConnect deployed!"
